[CI] changes

diff --git a/.github/workflows/bun-linux-build.yml b/.github/workflows/bun-linux-build.yml
--- a/.github/workflows/bun-linux-build.yml
+++ b/.github/workflows/bun-linux-build.yml
@@ -1,75 +1,51 @@
-name: bun-linux
-
-concurrency:
-  group: bun-linux-build-${{ github.ref }}
-  cancel-in-progress: true
+name: bun-linux-x64
 
 on:
   push:
     branches:
-      - main
-    paths:
-      - "src/**/*"
-      - "test/**/*"
-      - "packages/bun-usockets/src/**/*"
-      - "packages/bun-uws/src/**/*"
-      - "CMakeLists.txt"
-      - "build.zig"
-      - "Makefile"
-      - "Dockerfile"
-  pull_request:
-    branches:
-      - main
-    paths:
-      - "src/**/*"
-      - "test/**/*"
-      - "packages/bun-usockets/src/**/*"
-      - "packages/bun-uws/src/**/*"
-      - "CMakeLists.txt"
-      - "build.zig"
-      - "Makefile"
-      - "Dockerfile"
-  # Allows you to run this workflow manually from the Actions tab
+      - everything
+      - bisect
+  schedule:
+    - cron: '0 0 * * *'
   workflow_dispatch:
 
 jobs:
   linux:
     name: ${{matrix.tag}}
     runs-on: ${{matrix.runner}}
-    if: github.repository_owner == 'oven-sh'
     timeout-minutes: 90
     permissions: write-all
     strategy:
       fail-fast: false
       matrix:
         include:
-          - cpu: haswell
-            tag: linux-x64
-            arch: x86_64
-            build_arch: amd64
-            runner: big-ubuntu
-            build_machine_arch: x86_64
-            assertions: "OFF"
-            zig_optimize: "ReleaseFast"
-            target: "artifact"
-          - cpu: nehalem
-            tag: linux-x64-baseline
-            arch: x86_64
-            build_arch: amd64
-            runner: big-ubuntu
-            build_machine_arch: x86_64
-            assertions: "OFF"
-            zig_optimize: "ReleaseFast"
-            target: "artifact"
           # - cpu: haswell
-          #   tag: linux-x64-assertions
+          #   tag: linux-x64
+          #   arch: x86_64
+          #   build_arch: amd64
+          #   runner: ubuntu-latest
+          #   build_machine_arch: x86_64
+          #   assertions: "OFF"
+          #   zig_optimize: "ReleaseFast"
+          #   target: "artifact"
+          # - cpu: nehalem
+          #   tag: linux-x64-baseline
           #   arch: x86_64
           #   build_arch: amd64
           #   runner: big-ubuntu
           #   build_machine_arch: x86_64
-          #   assertions: "ON"
-          #   zig_optimize: "ReleaseSafe"
-          #   target: "artifact-assertions"
+          #   assertions: "OFF"
+          #   zig_optimize: "ReleaseFast"
+          #   target: "artifact"
+          - cpu: haswell
+            tag: linux-x64-assertions
+            arch: x86_64
+            build_arch: amd64
+            runner: big-ubuntu
+            build_machine_arch: x86_64
+            assertions: "ON"
+            zig_optimize: "ReleaseSafe"
+            target: "artifact-assertions"
           # - cpu: nehalem
           #   tag: linux-x64-baseline-assertions
           #   arch: x86_64
@@ -86,6 +62,35 @@ jobs:
           submodules: recursive
           ref: ${{github.sha}}
           clean: true
+      - name: check the date
+        run: |
+          for i in $(seq 0 23); do echo "T_MINUS_$i=$(date -d "$i hours ago" --iso=h)" >> $GITHUB_ENV; done
+      - name: check the date
+        run: |
+          for i in $(seq 0 7); do echo "T_MINUS_${i}_DAYS=$(date -d "00:00 $i days ago" --iso=h)" >> $GITHUB_ENV; done
+      - name: cache
+        uses: actions/cache@v4
+        with:
+          path: /tmp/cache
+          key: ${{env.T_MINUS_0}}
+          restore-keys: |
+            ${{env.T_MINUS_1}}
+            ${{env.T_MINUS_2}}
+            ${{env.T_MINUS_3}}
+            ${{env.T_MINUS_4}}
+            ${{env.T_MINUS_5}}
+            ${{env.T_MINUS_0_DAYS}}
+            ${{env.T_MINUS_1_DAYS}}
+            ${{env.T_MINUS_2_DAYS}}
+            ${{env.T_MINUS_3_DAYS}}
+      - name: install ccache
+        run: |
+          sudo apt-get install ccache
+          mkdir -p /tmp/cache/ccache
+          ccache -d /tmp/cache/ccache -s
+          ccache -d /home/runner/work/bun/bun/tmp/cache/ccache -s
+          ls -lR /tmp/cache || true
+          cp -av /tmp/cache cache
       - uses: docker/setup-buildx-action@v2
         id: buildx
         with:
@@ -101,13 +106,12 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
       - run: |
           mkdir -p /tmp/.buildx-cache-${{matrix.tag}}
+          mkdir -p /tmp/cache/ccache
       - name: Build and push
         uses: docker/build-push-action@v3
         with:
           context: .
           push: false
-          cache-from: type=local,src=/tmp/.buildx-cache-${{matrix.tag}}
-          cache-to: type=local,dest=/tmp/.buildx-cache-${{matrix.tag}}
           build-args: |
             ARCH=${{matrix.arch}}
             BUILDARCH=${{matrix.build_arch}}
@@ -116,12 +120,6 @@ jobs:
             GIT_SHA=${{github.sha}}
             ASSERTIONS=${{matrix.assertions}}
             ZIG_OPTIMIZE=${{matrix.zig_optimize}}
-            SCCACHE_BUCKET=bun
-            SCCACHE_REGION=auto
-            SCCACHE_S3_USE_SSL=true
-            SCCACHE_ENDPOINT=${{ secrets.CACHE_S3_ENDPOINT }}
-            AWS_ACCESS_KEY_ID=${{ secrets.CACHE_S3_ACCESS_KEY_ID }}
-            AWS_SECRET_ACCESS_KEY=${{ secrets.CACHE_S3_SECRET_ACCESS_KEY }}
           platforms: linux/${{matrix.build_arch}}
           target: ${{matrix.target}}
           outputs: type=local,dest=${{runner.temp}}/release
@@ -130,6 +128,9 @@ jobs:
         run: |
           # If this hangs, it means something is seriously wrong with the build
           ${{runner.temp}}/release/bun-profile --version
+      - id: cache-shuffle
+        run: |
+          cd /tmp && sudo tar xf ${{runner.temp}}/release/cache.tar
       - name: Zip
         run: |
           # if zip is not found
@@ -146,8 +147,6 @@ jobs:
 
           mkdir bun-${{matrix.tag}}-profile
           mkdir bun-${{matrix.tag}}
-
-          strip bun
 
           mv bun-profile bun-${{matrix.tag}}-profile/bun-profile
           mv bun bun-${{matrix.tag}}/bun
@@ -170,48 +169,47 @@ jobs:
         with:
           name: ${{matrix.tag}}-dependencies
           path: ${{runner.temp}}/release/bun-dependencies
-      - name: Release
-        id: release
-        uses: ncipollo/release-action@v1
-        if: |
-          github.repository_owner == 'oven-sh'
-          && github.ref == 'refs/heads/main'
-        with:
-          prerelease: true
-          body: "This canary release of Bun corresponds to the commit [${{ github.sha }}]"
-          allowUpdates: true
-          replacesArtifacts: true
-          generateReleaseNotes: true
-          artifactErrorsFailBuild: true
-          token: ${{ secrets.GITHUB_TOKEN }}
-          name: "Canary (${{github.sha}})"
-          tag: "canary"
-          artifacts: "${{runner.temp}}/release/bun-${{matrix.tag}}.zip,${{runner.temp}}/release/bun-${{matrix.tag}}-profile.zip"
-      - uses: sarisia/actions-status-discord@v1
-        if: failure() && github.repository_owner == 'oven-sh' && github.event_name == 'pull_request'
-        with:
-          title: ""
-          webhook: ${{ secrets.DISCORD_WEBHOOK }}
-          status: ${{ job.status }}
-          noprefix: true
-          nocontext: true
-          description: |
-            Pull Request
-            ### [${{github.event.pull_request.title}}](https://github.com/oven-sh/bun/pull/${{github.event.number}})
-
-            @${{ github.actor }}
-
-            Build failed on ${{ matrix.tag }}:
-
-            **[View build output](https://github.com/oven-sh/bun/actions/runs/${{github.run_id}})**
-
-            [Commit ${{github.sha}}](https://github.com/oven-sh/bun/commits/${{github.sha}})
+#       - name: Release
+#         id: release
+#         uses: ncipollo/release-action@v1
+#         if: |
+#           github.repository_owner == 'oven-sh'
+#           && github.ref == 'refs/heads/main'
+#         with:
+#           prerelease: true
+#           body: "This canary release of Bun corresponds to the commit [${{ github.sha }}]"
+#           allowUpdates: true
+#           replacesArtifacts: true
+#           generateReleaseNotes: true
+#           artifactErrorsFailBuild: true
+#           token: ${{ secrets.GITHUB_TOKEN }}
+#           name: "Canary (${{github.sha}})"
+#           tag: "canary"
+#           artifacts: "${{runner.temp}}/release/bun-${{matrix.tag}}.zip,${{runner.temp}}/release/bun-${{matrix.tag}}-profile.zip"
+#       - uses: sarisia/actions-status-discord@v1
+#         if: failure() && github.repository_owner == 'oven-sh' && github.event_name == 'pull_request'
+#         with:
+#           title: ""
+#           webhook: ${{ secrets.DISCORD_WEBHOOK }}
+#           status: ${{ job.status }}
+#           noprefix: true
+#           nocontext: true
+#           description: |
+#             Pull Request
+#             ### [${{github.event.pull_request.title}}](https://github.com/oven-sh/bun/pull/${{github.event.number}})
+#
+#             @${{ github.actor }}
+#
+#             Build failed on ${{ matrix.tag }}:
+#
+#             **[View build output](https://github.com/oven-sh/bun/actions/runs/${{github.run_id}})**
+#
+#             [Commit ${{github.sha}}](https://github.com/oven-sh/bun/commits/${{github.sha}})
   linux-test:
     name: Tests ${{matrix.tag}}
     runs-on: ubuntu-latest
     needs: [linux]
-    if: github.event_name == 'pull_request'
-    timeout-minutes: 20
+    timeout-minutes: 90
     permissions:
       pull-requests: write
     outputs:
@@ -221,9 +219,9 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - tag: linux-x64
-          - tag: linux-x64-baseline
-          # - tag: linux-x64-assertions
+          # - tag: linux-x64
+          # - tag: linux-x64-baseline
+          - tag: linux-x64-assertions
           # - tag: linux-x64-baseline-assertions
     steps:
       - id: checkout
@@ -271,40 +269,40 @@ jobs:
       #     # Core filenames will be of the form executable.pid.timestamp:
       #     sudo bash -c 'echo "/cores/%e.%p.%t" > /proc/sys/kernel/core_pattern'
 
+      - id: pretest
+        name: Pretest
+        run: |
+          node --version
+      - id: test2
+        name: Test (node runner)
+        run: |
+          ls -l packages/bun-internal-test/src/runner.node.mjs
       - id: test
         name: Test (node runner)
-        env:
-          SMTP_SENDGRID_SENDER: ${{ secrets.SMTP_SENDGRID_SENDER }}
-          TLS_MONGODB_DATABASE_URL: ${{ secrets.TLS_MONGODB_DATABASE_URL }}
-          TLS_POSTGRES_DATABASE_URL: ${{ secrets.TLS_POSTGRES_DATABASE_URL }}
-        # if: ${{github.event.inputs.use_bun == 'false'}}
         run: |
-          ulimit -c unlimited
-          ulimit -c
-
-          node packages/bun-internal-test/src/runner.node.mjs || true
+          node packages/bun-internal-test/src/runner.node.mjs
       - uses: actions/upload-artifact@v3
         if: steps.test.outputs.failing_tests != ''
         with:
           name: cores
           path: /cores
-      - uses: sarisia/actions-status-discord@v1
-        if: always() && steps.test.outputs.failing_tests != '' && github.event_name == 'pull_request'
-        with:
-          title: ""
-          webhook: ${{ secrets.DISCORD_WEBHOOK }}
-          status: "failure"
-          noprefix: true
-          nocontext: true
-          description: |
-            Pull Request
-            ### ❌ [${{github.event.pull_request.title}}](https://github.com/oven-sh/bun/pull/${{github.event.number}})
-
-            @${{ github.actor }}, there are ${{ steps.test.outputs.failing_tests_count }} files with test failures on ${{ matrix.tag }}:
-
-            ${{ steps.test.outputs.failing_tests }}
-
-            **[View test output](https://github.com/oven-sh/bun/actions/runs/${{github.run_id}})**
+ #      - uses: sarisia/actions-status-discord@v1
+ #        if: always() && steps.test.outputs.failing_tests != '' && github.event_name == 'pull_request'
+ #        with:
+ #          title: ""
+ #          webhook: ${{ secrets.DISCORD_WEBHOOK }}
+ #          status: "failure"
+ #          noprefix: true
+ #          nocontext: true
+ #          description: |
+ #            Pull Request
+ #            ### ❌ [${{github.event.pull_request.title}}](https://github.com/oven-sh/bun/pull/${{github.event.number}})
+ #
+ #            @${{ github.actor }}, there are ${{ steps.test.outputs.failing_tests_count }} files with test failures on ${{ matrix.tag }}:
+ #
+ #            ${{ steps.test.outputs.failing_tests }}
+ #
+ #            **[View test output](https://github.com/oven-sh/bun/actions/runs/${{github.run_id}})**
       - name: Comment on PR
         if: steps.test.outputs.failing_tests != '' && github.event_name == 'pull_request'
         uses: thollander/actions-comment-pull-request@v2
